export const team = [
  {
    name: 'Nazar Mural',
    position: 'Team Lead, Developer',
    description: 'Top-Books, API, ScrollUp, Function Button, HTML, SCSS',
    img: 'https://raw.githubusercontent.com/NazarMural/project-bookshelf/main/src/images/team/nazar-mural.jpg',
    url: 'https://github.com/NazarMural',
  },
  {
    name: 'Oleksii Maiok',
    position: 'Scrum, Developer',
    description: 'Shopping-List Page, API, Favicon, LocalStorage, HTML, SCSS',
    img: 'https://raw.githubusercontent.com/NazarMural/project-bookshelf/main/src/images/team/oleksii-maiok.jpg',
    url: 'https://github.com/moses35',
  },
  {
    name: 'Alona Kuznietsova',
    position: 'Developer',
    description: 'Category-Books, API, Loader, Footer+TeamModal, HTML, SCSS',
    img: 'https://raw.githubusercontent.com/NazarMural/project-bookshelf/main/src/images/team/alona-kuznietsova.jpg',
    url: 'https://github.com/acvetochka',
  },
  {
    name: 'Kate Chernysheva',
    position: 'Developer',
    description: 'Firebase, SingUp-SingIn Modal Windows, HTML, SCSS',
    img: 'https://raw.githubusercontent.com/NazarMural/project-bookshelf/main/src/images/team/kate-chernysheva.jpg',
    url: 'https://github.com/kateChernysheva1',
  },
  {
    name: 'Tetiana Palii',
    position: ' Developer',
    description: 'Modal Window Book-Description, API, HTML, SCSS',
    img: 'https://raw.githubusercontent.com/NazarMural/project-bookshelf/main/src/images/team/tetiana-palii.jpg',
    url: 'https://github.com/TetiPalii',
  },
  {
    name: 'Masha Kozlova',
    position: 'Developer',
    description: 'ShoppingList, HTML, SCSS',
    img: 'https://raw.githubusercontent.com/NazarMural/project-bookshelf/main/src/images/team/masha-kozlova.jpg',
    url: 'https://github.com/Maniyavel',
  },
  {
    name: 'Nataliia Korotych',
    position: 'Developer',
    description: 'Header, Mobile Menu, HTML, SCSS',
    img: 'https://raw.githubusercontent.com/NazarMural/project-bookshelf/main/src/images/team/nataliia-korotych.jpg',
    url: 'https://github.com/Nataliia-84',
  },
  {
    name: 'Viktoriia Khmelevska',
    position: 'Developer',
    description: 'Support Ukraine, Swiper, HTML, SCSS',
    img: 'https://raw.githubusercontent.com/NazarMural/project-bookshelf/main/src/images/team/viktoriia-khmelevska.jpg',
    url: 'https://github.com/ViktoriiaKhmelevska',
  },
];
